### ISSUE TITLE
Increase max http sockets

### ISSUE THREAD

**Issue by jazzzz** [stianeikeland/node-etcd#23]
The `request` instance in `node-etcd` uses the default http agent, thus we are limited to 5 concurrent requests for a single etcd instance, which is rather low. I think it would be safe to set a high value using `request` `pool.maxSockets` option.

**Comment by ravi** [comment]
FYI, I have an environment with many hundred NodeJS servers connecting to EtcD using this module, and the above setting (IIUC), is causing thousands of TCP connections being held at the EtcD server end.
