### ISSUE TITLE
Synchronous Support

### ISSUE THREAD

**Issue by brockwood** [stianeikeland/node-etcd#35]
Greetings,

I have added synchronous support to node-etcd and I was curious if there is any interest in a pull request to possibly take this work.  Specifically, my changes add synchronous versions of get, set, del, mkdir, and rmdir.  This work utilizes the requestsync module.  Please let me know.  Thanks!

**Comment by brockwood** [comment]
If interesting, here's what would change:  

https://github.com/brockwood/node-etcd/commit/f1587677b170190c77fc7c5a77caf75d75d46e94

**Comment by stianeikeland** [comment]
Hello, sorry for late reply

Yeah, I think that could be useful.
I guess many use etcd when their program is starting up, just like the node fs module.

Could you add a few tests covering the new functions and send a PR?

Thanks!

**Comment by brockwood** [comment]
Awesome!  I'll submit a PR in the next 24 hours.  Thanks again!

**Comment by brockwood** [comment]
Pull request is at https://github.com/stianeikeland/node-etcd/pull/36 and any feedback is greatly welcome.

**Comment by stianeikeland** [comment]
Merged in #36
