### ISSUE TITLE
SSL broken

### ISSUE THREAD

**Issue by psi-4ward** [stianeikeland/node-etcd#39]
[client.js](https://github.com/stianeikeland/node-etcd/blob/master/src/client.coffee#L96) uses the `request` module which has its own [SSL support](https://github.com/request/request#tlsssl-protocol)

[Setting up an HttpAgent](https://github.com/stianeikeland/node-etcd/blob/master/src/index.coffee#L240) dont work (anymore)

Probably it should:

```coffeescript
    if @sslopts?
      serverprotocol = "https"

    opt = {
      path: "#{apiVersion}/#{path}"
      serverprotocol: serverprotocol
      json: true
      agentOptions: #{sslopts}
      qs: queryString
      clientOptions: clientOptions
      synchronous: allOpts.synchronous
      form: { value: value } if value?
    }
```

sorry for not creating a pull-request but coffee is something to dring ;)

**Comment by stianeikeland** [comment]
Thanks, will take a look at that!

Bumped request version (we used a pretty old one before) recently, 
and that probably broke something.

**Comment by stianeikeland** [comment]
Hmm, I'm having trouble reproducing this one, am I missing something?

First I start an etcd instance with ssl support:
```
$ etcd \
    -name=banan \
    -data-dir=banan \
    -ca-file=ca.crt \
    -cert-file=server.crt \
    -key-file=server.key \
    -force-new-cluster \
    -advertise-client-urls=https://127.0.0.1:2379 \
    -listen-client-urls=https://127.0.0.1:2379
```

Set and get a value using etcdctl, using the same keys as server for simplicity.

```
$ etcdctl \
    -ca-file=ca.crt \
    -key-file=server.key \
    -cert-file=server.crt \
    -peers=https://127.0.0.1:2379 \
    set test zing
$ etcdctl \
    -ca-file=ca.crt \
    -key-file=server.key \
    -cert-file=server.crt \
    -peers=https://127.0.0.1:2379 \
    get test
zing
```

Create a small test program:

``` coffee
Etcd = require 'node-etcd'
fs = require 'fs'

sslopts =
    ca: [ fs.readFileSync 'ca.crt' ]
    cert: fs.readFileSync 'server.crt'
    key: fs.readFileSync 'server.key'

etcdssl = new Etcd 'localhost', '2379', sslopts

log = (err, data) ->
  console.log "error: %j", err
  console.log "output: %j", data

etcdssl.get "test", log
```

Run it:
```
$ coffee test.coffee
error: null
output: {"action":"get","node":{"key":"/test","value":"zing","modifiedIndex":3,"createdIndex":3}}
```

If I give it an invalid cert:
```
$ coffee test.coffee
error: {"errors":[{"server":"localhost:2379","httperror":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"timestamp":"2015-04-16T20:21:52.096Z"}],"retries":0}
output: undefined
```

**Comment by psi-4ward** [comment]
According your `etcdctl` i assume you are using version 2.0 cause 0.4 has no support for the `-cert-file` in `etcdctl`.

I have 0.4 here (CoreOS). 

The next thing: Youre using a 1-node-cluster right?
Ive several nodes here and in <2.0 you have to "speak" to the leader. A request to any follower results in an `Status 307 Location: https://leader_ip ...`. While exploring the problem i wondered why i get the 307 Redirect and the next request fails! So perhaps `request()` respects the httpsAgent the first time but not when contstructing the next requests to follow the redirection?

**Comment by stianeikeland** [comment]
Aha, that makes more sense..
Yeah, I think you're right regarding the 307 redirect and httpsAgent not working the second time.

I will setup a multi-node cluster then and try again.

**Comment by stianeikeland** [comment]
Confirmed, request library forgets about the httpsagent when receiving a 307 redirect from etcd cluster on 0.4. The https agent stuff

```2015/04/16 23:25:35 http: TLS handshake error from 127.0.0.1:49393: tls: client didn't provide a certificate```

Fix released as 4.0.2, could you try it out? :)

Thank you for reporting.

**Comment by psi-4ward** [comment]
Yeaaahhh let my try

Here is another tool using your great lib: https://github.com/psi-4ward/docker-etcd-registrator

**Comment by psi-4ward** [comment]
works perfect!

How can i get you a beer?

**Comment by stianeikeland** [comment]
That's great, thanks! :)
Haha, give me a ping on the off-chance you ever end up near western Norway :beers: :+1:

**Comment by psi-4ward** [comment]
And you ping me when youre in germany ;) (y)
