### ISSUE TITLE
getSync is dying

### ISSUE THREAD

**Issue by esk1989** [stianeikeland/node-etcd#42]
By using the "lab" to perform unit testing, the getSync dies, allowing not continue testing.
Searching in the code, I found that the error occurs in the file "./node_modules/node-etcd/node_modules/deasync/index.js" on line 54, the command "binding.run ()", also found that the command exists but the run him to the "lab".

**Comment by shakefu** [comment]
I'm also seeing getSync hanging in mocha tests when used in the module context.

**Comment by stianeikeland** [comment]
Thanks!
Should be fixed in v4.2.1
