### ISSUE TITLE
Update deasync dependency to 0.1.1 for io.js 3.3.0 support

### ISSUE THREAD

**Issue by jhurliman** [stianeikeland/node-etcd#43]
deasync depends on a package called nan that was failing to build on the latest version of io.js until recently. nan has been fixed and a new version of deasync has been released to update the dependency, but currently node-etcd is pinned to 0.0.x versions of deasync.

**Comment by stianeikeland** [comment]
Currently travelling, so I havn't had much time to debug.
Tried bumping to v0.1.1, but still seems to fail:
https://travis-ci.org/stianeikeland/node-etcd/builds/78788187

#42 is probably related.

**Comment by stianeikeland** [comment]
This seems relevant:
https://github.com/abbr/deasync/issues/27#issuecomment-136085550

**Comment by xFragger** [comment]
For node 4.0 it fails when installing deasync
> deasync@0.0.10 install /Users/michaelfreund/phpStormProjects/shopgate/module-etcd-nodejs/node_modules/node-etcd/node_modules/deasync
> node ./build.js

But an npm install deasync installs 0.1.1 without problems

**Comment by jhurliman** [comment]
It looks like there is an open branch to fix this <https://github.com/stianeikeland/node-etcd/compare/fix-deasync>. Any idea on ETA for a new release?

**Comment by stianeikeland** [comment]
I still have breaking tests on travis-ci for iojs, so don't want to release just yet until I figure it out.
but could you test out `npm install node-etcd@deasync`?

**Comment by stianeikeland** [comment]
Managed to figure it out, travis-ci is too old to build nodejs 4.0.0, which caused node-gyp to fail, it requires a newer c++ compiler.

Released as 4.2.1

Thanks!
