### ISSUE TITLE
Is there a way to subscribe for the key?

### ISSUE THREAD

**Issue by PavelPolyakov** [stianeikeland/node-etcd#49]
Hi,

In the library description the next options are described:
1/ 
```javascript
etcd.get('key', {wait: true}, callbeck)
```
2/
```javascript
let watcher = etcd.watcher("key");

watcher.on('change', (data) => {
    console.log(data);
});
```

Each of these allows us to receive a key on update, however, when the application is started - we would not receive any. In case of `{wait: true}` it would leave the event loop after the first change.

Is there a way to subscribe for the key update with the next criteria:
1. We get the value when the application is started
2. We receive any updates of the key each time the key is updated

Any thoughts?

Regards,

**Comment by stianeikeland** [comment]
You could try setting a really low index value when using the watcher.
```javascript
var etcd = new Etcd('127.0.0.1:4001');
var watcher = etcd.watcher('key', 1);
watcher.on("change", console.log);
```
Setting an index value means you want any changes after the given index. I think etcd starts at 100, so index 1 will always return immediately.

**Comment by PavelPolyakov** [comment]
Correct, this concept is working, I have checked. Thanks.
