### ISSUE TITLE
how to check if etcd is connected or we put some trash servers as hosts

### ISSUE THREAD

**Issue by PavelPolyakov** [stianeikeland/node-etcd#50]
Hi,

When I execute the code like this:

```javascript
'use strict';

const Etcd = require('node-etcd');
const etcd = new Etcd(['yandex.ru:4001']);


etcd.set('key','value', (err, data) => {
        console.log('err', err);
        console.log('data', data);
});
```

It will just starts and waits for a long time. Then I see the error:
```
{ [Error: All servers returned error]
  errors:
   [ { server: 'yandex.ru:4001',
       httperror: [Object],
       httpstatus: undefined,
       httpbody: undefined,
       response: undefined,
       timestamp: Sun Dec 20 2015 21:23:07 GMT+0100 (CET) } ],
  retries: 0 }
```

From my point of view, it takes too long to identify that `hosts` are not okay.
Is there a way to synchronously check if something is wrong or not? Where it's possible to setup the error timeout? 

Regards,

**Comment by stianeikeland** [comment]
I've added support for setting timeout in the latest beta release.
Could you try `npm install node-etcd@beta`?

https://github.com/stianeikeland/node-etcd#constructor-options

**Comment by PavelPolyakov** [comment]
Just checked, works as expected. Thanks!

**Comment by trystanj** [comment]
@stianeikeland are there any plans to release v5 to npm? The new constructor options would be great to have!

**Comment by stianeikeland** [comment]
@trystanj - released now, sorry about the wait :)

**Comment by trystanj** [comment]
Thank you! This is super helpful (and better than relying on "beta") :)
