### ISSUE TITLE
https without a cert

### ISSUE THREAD

**Issue by MattCollins84** [stianeikeland/node-etcd#59]
I want to be able to specify a `https` connection string, but not have to pass in a certificate - at the moment it seems like passing in a `https` URL automatically requires me to supply a cert.

You can use the `rejectUnauthorized` param from here: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback and pass it into the `agentOptions` of `request` in this instance to make this work (I think!).

I would attempt a PR, but Coffee script is very alien to me and I don't want to break things :)

Thanks!

**Comment by DerekTBrown** [comment]
Not sure this is worth a PR.  The whole point of a HTTPS-encrypted endpoint is to ensure authority of a server.  You should really either use HTTP (so there is no illusion of security) or download the certificates ahead of time.
